name: Latest Dev.to Articles
on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest Dev.to posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/thesyntaxdude"
